filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/nginx/access.log
  tags: ["accesslog"]
- type: filestream
  enabled: true
  paths:
    - /var/log/nginx/error.log
  tags: ["errorlog"]

# - type: filestream
#   enabled: true
#   paths:
#     - /home/logs/only
#   tags: ["vm1_home_only"]
  
# filebeat.config.modules:
#   path: ${path.config}/modules.d/*.yml
#   reload.enabled: false


    #filebeat.autodiscover:
    # proveiders:
    #    - type: docker
    #      hints.enabled: true
    #      tags: ["containers"]



filebeat.config:
  modules:
    path: /usr/share/filebeat/modules.d/*.yml



# filebeat.modules:
# - module: nginx
#   access:
#     var.paths: ["/var/log/nginx/access.log*"]
#   error:
#     var.paths: ["/var/log/nginx/error.log*"]




####### OutPut
setup.kibana:
 host: http://kibana:5601
 username: elastic
 password: qwe123rty456

output.elasticsearch:
  hosts: http://es01:9200
  username: elastic
  password: qwe123rty456
  ssl.enabled: true
  indices:
  - index: "access-log-%{+yyyy.MM.dd}"
    when.contains:
      tags: "accesslog"
  - index: "error-log-%{+yyyy.MM.dd}"
    when.contains:
      tags: "errorlog"
  - index: "containers-%{+yyyy.MM.dd}"
    when.contains:
      tags: "containers"

  # - index: "cloud-init-%{+yyyy.MM.dd}"
  #   when.containes:
  #     tags: "cloud-init"


# output.logstash:
#   hosts: ["logstash.kavosh.org:15044"]
